                         #\\\\\\\\\\\\\\\/////////////////#
                         ###      HYPRLAND SOURCES      ###
                         #\\\\\\\\\\\\\\\/////////////////#
#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\//////////////////////////////////////////////////#

# Configuration Files:

source = $HOME/.config/hypr/configs/aesthetics.conf                                # Controls visual settings like themes and wallpapers.
source = $HOME/.config/hypr/configs/autostart.conf                                 # Defines applications to launch on startup.
source = $HOME/.config/hypr/configs/environment.conf                               # Sets environment variables and system behavior.
source = $HOME/.config/hypr/configs/input_rules.conf                               # Specifies input device rules.
source = $HOME/.config/hypr/configs/monitors.conf                                  # Configures monitor layout and resolution.
source = $HOME/.config/hypr/configs/variables.conf                                 # General variables affecting the system.
source = $HOME/.config/hypr/configs/window_rules.conf                              # Window-specific rules for behavior.
source = $HOME/.config/hypr/configs/keybindings.conf                               # Defines Hyprland, and User Defined keybindings.

# More info: https://wiki.hyprland.org

#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\//////////////////////////////////////////////////#