                                    ###############################
                                    ### AUTOSTART CONFIGURATION ###
                                    ###############################
#/||--------------------------------------------------------------------------------------------||\#

# For more info, check the documentation: https://wiki.hyprland.org

#/||--------------------------------------------------------------------------------------------||\#

### Desktop Experience ###

exec-once = hypridle
exec-once = hyprpaper
exec-once = waybar
exec-once = wal -i "$(< "${HOME}/.cache/wal/wal")"
exec-once = swaync
exec-once = vesktop
exec-once = $musicPlayer

#/||--------------------------------------------------------------------------------------------||\#