                                    #################################
                                    ### ENVIRONMENT CONFIGURATION ###
                                    #################################
#/||--------------------------------------------------------------------------------------------||\#

# For more info, check the documentation: https://wiki.hypr.land/Configuring/Environment-variables/

#/||--------------------------------------------------------------------------------------------||\#

### System Settings ###

env = XDG_SESSION_TYPE=hyprland

### VULKAN & EGL Settings ###

env = __NV_PRIME_RENDER_OFFLOAD=1
env = VK_LAYER_PATH=/usr/share/vulkan/explicit_layer.d

### Open GL Settings ###

env = __GL_THREADED_OPTIMIZATIONS=1     # Optional

### Electron Apps ###
env = WLR_NO_HARDWARE_CURSORS=1
env = ELECTRON_OZONE_PLATFORM_HINT=auto

### Wayland Compositor ###

env = WLR_RENDERER_ALLOW_SOFTWARE=0     # Optional
env = MOZ_ENABLE_WAYLAND=1
env = GDK_BACKEND=wayland
env = QT_QPA_PLATFORM=wayland;xcb
env = QT_AUTO_SCREEN_SCALE_FACTOR=1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION=1
env = QT_QPA_PLATFORMTHEME=kvantum
env = QT_STYLE_OVERRIDE=kvantum

### Appearance Settings ###


env = gtk-cursor-theme-size=24
env = XCURSOR_SIZE=24
env = HYPRCURSOR_SIZE,24
env = QT_CURSOR_SIZE,24

### Performance Tweaks ###

env = HYPRLAND_DISABLE_ANIMATIONS=false # Optional

### Cursor Settings ###

#cursor {
#    no_hardware_cursors = true
#}

#/||--------------------------------------------------------------------------------------------||\#
