                                    #############################
                                    ### MONITOR CONFIGURATION ###
                                    #############################
#/||--------------------------------------------------------------------------------------------||\#

# For more info on monitor configuration, visit: https://wiki.hyprland.org/Configuring/Monitors/

#/||--------------------------------------------------------------------------------------------||\#

# Primary Monitor
monitor = eDP-1, 1920x1080@60, 0x0, 1

#/||--------------------------------------------------------------------------------------------||\#

# Set Displays
$display1 = DP-1

#/||--------------------------------------------------------------------------------------------||\#