                                    #############################
                                    ### MONITOR CONFIGURATION ###
                                    #############################
#/||--------------------------------------------------------------------------------------------||\#

# For more info on variables and their use, visit: https://wiki.hyprland.org/Configuring/Variables/

#/||--------------------------------------------------------------------------------------------||\#

### Super Key ###

$mainMod = SUPER

### Default Applications ###

$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun
$browser = chromium
$waybarRelaunch = ~/.config/waybar/scripts/launch.sh
$discord = vesktop
$editor = zed
$musicPlayer = chromium --app-id=blgdilankhbcpipclgpdndahbehalgkh


### Directories ###

$wallpapers = $HOME/dotfiles/wallpapers/

### Hyprlock ###
$profile-picture-path = 
$desktop-logo-path = 

#/||--------------------------------------------------------------------------------------------||\#