                            ########################################
                            ### WINDOW/LAYER RULES CONFIGURATION ###
                            ########################################
#/||--------------------------------------------------------------------------------------------||\#

# For more info, visit: https://wiki.hypr.land/Configuring/Window-Rules/

#/||--------------------------------------------------------------------------------------------||\#

### Window Rules ###

# Float file picker windows
windowrule = match:title ^(Open File|Open Folder|Open Image|Open|Save|Save As|Export|Import|Choose File|Rename), float yes, center yes, size 800 600

# Float system control apps
windowrule = match:class ^(org.pulseaudio.pavucontrol|Impala|bluetui|Syu|nwg-look), float yes, move 610 47, size 700 700, animation slide 90%

# Media Apps
windowrule = match:class vesktop, workspace special:media silent
windowrule = match:class chrome-blgdilankhbcpipclgpdndahbehalgkh-Default, workspace special:media silent

# Zed

windowrule = match:class dev.zed.Zed, opacity 0.8

### Layer Rules ###

# Waybar
layerrule = blur on, match:namespace waybar

# Wlogout
layerrule = blur on,  match:namespace logout_dialog

# Rofi
layerrule = dim_around on, blur on, animation popin 90%,  match:namespace rofi

# Swaync
layerrule = blur on, ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = blur on, ignore_alpha 0.5, match:namespace swaync-notification-window

#/||--------------------------------------------------------------------------------------------||\#